name: Daily Stock Update
on:
  schedule:
    - cron: '30 10 * * *' # This runs at 4:00 PM IST every day
  workflow_dispatch: # This adds a button to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install libraries
        run: pip install google-cloud-bigquery requests pandas db-dtypes pandas-gbq

      - name: Run script
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
          ALPHA_VANTAGE_KEY: ${{ secrets.ALPHA_VANTAGE_KEY }}
        run: python main.py
        
